Write integration tests
emmiiorji/my_blog pull request #15
Opened 2022-11-03 15:07 UTC by emmiiorji

This change adds test for the index and show views of posts and users.

2022-11-03 16:10 UTC, DeliceLydia requested changes
## Hi @emmiiorji, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


### Cheers!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-03 16:10 UTC, DeliceLydia commented on app/controllers/posts_controller.rb
> +    @posts = @user ? Post.where(author: @user).paginate(page: params[:page], per_page: 5) : nil
- [ ] To solve the N+1 issue to be able to fetch all posts and their comments for a user you can simply do:
`@posts = @user.posts.includes(:comments)`

2022-11-03 16:10 UTC, DeliceLydia commented on spec/features/users/show.html.erb_spec.rb
> +end
- [ ] Please fix one test that is failing
![Screenshot from 2022-11-03 17-55-22](https://user-images.githubusercontent.com/44745855/199772940-b1469bd0-0115-4bea-89dd-db652be7b04f.png)

2022-11-03 16:14 UTC, emmiiorji commented on app/controllers/posts_controller.rb
> +    @posts = @user ? Post.where(author: @user).paginate(page: params[:page], per_page: 5) : nil
Hi @DeliceLydia,

Thanks for the kind review.

We don't seem to get a warning from bullet about it. We have the [bullet gem](https://github.com/flyerhzm/bullet) installed which checks for n+1 queries. We've solved the issues it identified as n+1 queries.

2022-11-04 05:00 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @emmiiorji and @HansZizold, 

Good job implementing the changes requested by the previous reviewer.
To highlight 👍🏽 
- You wrote integration tests
- Your tests pass

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 


![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-11-04 07:33 UTC, merged